### ISSUE TITLE
Wrong percentile result

### ISSUE THREAD

**Issue by ankurparihar** [shlomif/perl-Statistics-Descriptive#7]
```
use Statistics::Descriptive;
my $latencystat = Statistics::Descriptive::Full->new();

$latencystat->clear();
$latencystat->add_data(1, 1, 1, 1, 1, 1, 1, 1, 1, 1);
print ($latencystat->count(), " ", $latencystat->mean(), " ", $latencystat->percentile(99), "\n");
```

Results in
10 1 19

Expected
10 1 1

Perl version is 5

**Comment by shlomif** [comment]
This is due to list context. this works:

```
#! /usr/bin/env perl

use strict;
use warnings;
use 5.014;
use autodie;

use Statistics::Descriptive;
my $latencystat = Statistics::Descriptive::Full->new();

$latencystat->clear();
$latencystat->add_data(1, 1, 1, 1, 1, 1, 1, 1, 1, 1);
print ($latencystat->count(), " ", $latencystat->mean(), " ", scalar($latencystat->percentile(99)), "\n");
```

can this ticket be closed?

**Comment by shlomif** [comment]
@ankurparihar :

**Comment by ankurparihar** [comment]
Thanks for reaching out. Haven't tried this yet.

It can be closed.

**Comment by shlomif** [comment]
> Thanks for reaching out. Haven't tried this yet.
> 
> It can be closed.

closing then.

**Comment by eritain** [comment]
I experience this contextual behavior of `percentile()` as a misfeature. 

Lists of percentile values are a frequent use case for me (as summaries of distributions). 

When working with list values, I usually strongly prefer list processing functions like `map` over writing boilerplate list-accumulator loops: `my  @foo; push @foo, $stat->percentile($_ * 10) for 1..9;` 

I think `map` expressions describe intent better, and I enjoy being able to write them right where the value is consumed, instead of having to set them up ahead of time in statements, devise a sufficiently readable name for the intervening variable, etc.

Every time I step away from `Statistics::Descriptive` for more than a day, when I come back `percentile()`'s weird context-sensitivity bites me again. If not in a `map` expression, then in a `say` expression like the original filer of this issue. It's an ever-flowing fountain of inscrutable bugs.

Getting the index of the percentile value is never my use-case, and if it were, I'd expect it to have its own method, not be a parasitic appendage of this one.

I know backwards compatibility is Very Important, but I'd love to see this behavior hidden behind a flag (with deprecation warnings for a suitable length of time first), and a single value returned regardless of context. 

(Or, if people who do use the index are in the majority, make `percentile()` return an arrayref in all contexts. Then value-only weirdos like me will have to suffer a deprecation cycle too.)
